USE SP_OLAUBER_SERVICE;
SELECT * FROM SP_UO_DATA WHERE PIC_LOCT = 'MANINAGAR' AND CAR_NAME = 'SWIFT';
SELECT * FROM SP_UO_DATA WHERE PIC_LOCT = 'MANINAGAR' AND STATUS = 'ONTIME';

SELECT * FROM SP_UO_DATA WHERE PIC_LOCT = 'MANINAGAR' OR CAR_NAME = 'SWIFT';
SELECT * FROM SP_UO_DATA WHERE PIC_LOCT = 'MANINAGAR' OR STATUS = 'ONTIME';

SELECT * FROM SP_UO_DATA WHERE NOT PIC_LOCT = 'MANINAGAR';
SELECT * FROM SP_UO_DATA WHERE NOT STATUS = 'ONTIME';

SELECT * FROM SP_UO_DATA ORDER BY RIDE_DATE;
SELECT * FROM SP_UO_DATA ORDER BY D_NAME DESC;
SELECT * FROM SP_UO_DATA ORDER BY PIC_TIME ASC, DEOP_TIME DESC;


SELECT MIN(RIDE_PRICE) AS SmallestPrice FROM SP_UO_DATA;
SELECT MAX(RIDE_PRICE) AS SmallestPrice FROM SP_UO_DATA;


SELECT * FROM SP_UO_DATA WHERE RIDE_PRICE BETWEEN 1000 AND 5000;
SELECT * FROM SP_UO_DATA WHERE PIC_TIME BETWEEN 21 AND 24;

SELECT * FROM SP_UO_DATA WHERE RIDE_PRICE BETWEEN 1000 AND 7000 AND D_ID NOT IN (101,202,300);
SELECT * FROM SP_UO_DATA WHERE RIDE_DATE BETWEEN '2023-01-12' AND '2023-01-31' ORDER BY RIDE_DATE;


