use uaes_idd;
CREATE TABLE home_work (
    HW_ID int NOT NULL,
    HW_SUB varchar(255) NOT NULL,
    HW_CLASS varchar(255) NOT NULL,
    HW_MARKS int NOT NULL
);

-- UNION
-- SAME COLLUM AND DATA
SELECT HW_ID FROM home_work
UNION
SELECT HW_ID2 FROM home_work2;

-- DIFFRENT DATA AND SAME DATATYPE(INT)
SELECT HW_ID FROM home_work
UNION
SELECT HW_CLASS FROM home_work2;

-- DIFFRENT COLLUM AND DIFFRENT DATA TYPE(INT AND VARCHAR)
SELECT HW_ID FROM home_work
UNION
SELECT HW_sub2 FROM home_work2;

-- EXIST
SELECT HW_SUB FROM home_work WHERE EXISTS (SELECT HW_MARKS2 FROM home_work2 WHERE home_work.HW_ID = home_work2.hw_id2 AND HW_CLASS < 20);

-- SELF JOIN
SELECT A.HW_CLASS AS HW_CLASS11, B.HW_MARKS AS HW_MARKS22, A.HW_SUB FROM home_work A, home_work B
WHERE A.HW_ID <> B.HW_ID AND A.HW_SUB = B.HW_SUB
ORDER BY A.HW_SUB;

SELECT HW_SUB
FROM home_work, home_work2
WHERE HW_ID and hw_sub order by HW_SUB;

-- ANY & ALL
SELECT HW_SUB FROM home_work WHERE HW_ID = ANY (SELECT HW_ID2 FROM home_work2 WHERE HW_MARKS > 80);

SELECT HW_SUB FROM home_work WHERE HW_ID = ANY (SELECT HW_ID2 FROM home_work2 WHERE HW_MARKS = 60);

SELECT HW_SUB FROM home_work WHERE HW_ID = ANY (SELECT HW_ID2 FROM home_work2 WHERE HW_MARKS < 80);


